città:
        - "musica/city1.mp3"
        - "musica/city2.mp3"

taverna:
        - "musica/taverna2.mp3"

viaggio:
        - "musica/viaggio1.mp3"
        
briganti:
        - "musica/briganti1.mp3"
        

assassini:
        - "musica/assassini1.mp3"

gilda:
        - "musica/gilda1.mp3"