#+TITLE: NPC

* Uomo Incappucciato
:PROPERTIES:
:DOVE: Taverna?
:END:
Uomo di mezza età (tra i 40 e i 50 anni)

* Mastro Fernand
:PROPERTIES:
:RUOLO: Direttore della Gilda
:LUOGO: Gilda della cittadina di inizio
:RAZZA: Umano M
:END:
Uomo all'inizio della terza età. Basso e tarchiato, presenta una folta
barba bianca sulle guance, che si collegano poi a delle spesse
basette.  Basette che contrastano la vistosa mancanza di
capelli. Fernand è un uomo affabile e allegro, nonostante l'età gli
occhi si presentano vispi e curiosi. Le parole, anche se dette con
tono convenevole e allegro, tradiscono una grande esperienza.

* Garret
:PROPERTIES:
:RUOLO: Assistende del direttore di Gilda
:LUOGO: Gilda della cittadina di inizio
:RAZZA: Mezzo Elfo M
:END:
Senza barba o baffi, si presenta con l'aspetto di un giovane uomo dai
lunghi capelli biondi. Di costituzione longilinea, ha un colore della
pelle molto chiaro.  Ha un modo di fare diplomatico. Non sembra mai
perdere la calma, ma sa farsi rispettare, specialmente dagli
avventurieri più rumorosi di stanza alla Gilda.

* Re Sangeris I
:PROPERTIES:
:RUOLO: Re del regno di Thay
:LUOGO: Stanza del trono
:RAZZA: Umano M
:END:
Unico monarca del regno, nel tempo ha promulgato una serie di leggi a
favore di maghi e collegi di stregoneria. È stato lui ad istituire il
corpo di esploratori. Grande utilizzare di magia, a corte di dice che
con il tempo abbia sviluppato un'ossessione per gli oggetti magici.

* Sir Abien
:PROPERTIES:
:RUOLO: Capitano del II regimento del corpo degli esploratori di sua maestà
:LUOGO: Prima parte del viaggio (fino alla capitale)
:RAZZA: Umano M
:END:
Uomo dall'altezza media. Capelli lunghi, raccolti in una coda, e
castani. La maggior parte del tempo lo si vede indossare l'uniforme, del
[[file:Gruppi.org::*Corpo di esploratori di sua Maestà][Corpo di esploratori di sua Maestà]].


