#+TITLE: La coda della Volpe
#+AUTHOR: Mario Calcagno

* Sinopsi
È sera.
La storia incomincia con il party all'interno dell'aticamera
dell'ufficio del direttore della Gilda di <<X>>.

* Missione
Esplorare un dungeon ai limiti del regno

* Prologo
Vi ritrovare in una stanza ampia, con sedie e panche lungo i muri.
Sul pavimento un ampio tappeto color verde erba adornato con ricami in
oro lungo il bordo. Ricami ripresi da una serie di stendardi in due
tonalità di verde alternate, appesi sulle pareti. Gli stendardi sono
decorati con una serie di stemmi araldici. Di fronte a voi una porta
di castagno a due ante. Dopo una leggera attesa vedete uscire un
mezz'elfo [[file:NPC.org::*Garret][Garret]] dai capelli lunghi e biondi e dal viso giovane.

GARRET: "Mi scuso per l'attesa, [[file:NPC.org::*Mastro Fernand][Mastro Fernand]] è pronto ad accogliervi".

Entrate in un ampio ufficio. Venite accolti da un grosso camino
scricchiolante, notate tra le fiamme dei rametti di alloro vivo.
Nell'ufficio si sente un leggero odore di incenso. Fernand vi accoglie
con un grosso sorriso, con una pipa in mano, anche se i suoi occhi
vi osservano con sguardo attento. Dopo due sbuffi di pipa, Mastro Fernand
si sistema sulla sedia ed inizia:

FERNAND: "Benvenuti avventurieri, vi chiederete perché la gilda vi 
abbia chiamato. Ognuno di voi è stato scelto, per le proprie particolari
abilità. La vostra missione è esplorare l'ultimo dungeon scoperto
dal corpo di esplorazione di sua Maestà Sangeris I"

                            SPAZIO DOMANDE

FERDAND: "Ora che è tutto chiaro potete dirigervi verso il salone
dove Garret vi comunicherà i dettagli più noiosi"

Dopo aver parlato con Garret, vi dirigete verso la locanda cittadina
in cui prendete stanza e dormite fino all'alba del giorno dopo.

* Il viaggio
È mattina, fuori dalla locanda vi aspettano due carrozze, sulle porte
notate lo stemma reale. Dalla prima carrozza vedete scendere un uomo
dai capelli castani, raccolti in una coda. L'uomo si presenta come [[file:NPC.org::*Sir Abien][Sir
Abien]], capitano del II reggimento del [[file:Gruppi.org::*Corpo di esploratori di sua Maestà][Corpo di esploratori di sua
Maestà]]. Vi mostra un documento, firmato dal Re, che farà da lascia
passare per la capitale. Sir Abien vi invita a salire sulle carrozze
per partire al più presto. Il viaggio sarà lungo.

